// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqhravgjywrttvjynvqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxaHJhdmdqeXdydHR2anludnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDY1NDcsImV4cCI6MjA4Njc4MjU0N30.QbdCQbn_FrtIXvTsE-wx9tRO_zVTSQ-Yxr3nQ_tNJak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});